### PR TITLE
Documentation and License Cleanup

### PR DESCRIPTION
**Pull request by swashcap**
- **Problems:**
  - Not every package has a license
  - We’re referencing old (pre-monorepo) assets and URLs
- **Solution:** Update it!
- **Testing:** Examine commit messages for topical overview, then confirm I didn’t miss any references in READMEs and _package.json_s.

### CODE REVIEW

**Comment by swashcap** [comment]
@rssk If/when you merge, please add “Closes #25” in the message.

**Comment by rssk** [comment]
Whew, a lot of doc changes, ??

[--- Commented from Asana.com
#commenter coins
---[aa]

**Comment by swashcap** [comment]
> Whew, a lot of doc changes, ??

Yeah, mostly updates for the monorepo and some minor fixes for consistency.

Rebased, so it's ready for mergin’ ⤴️

**Comment by swashcap** [comment]
@rssk This is ready. Good to merge?

**Pull request merged**
