### PR TITLE
Fix log out crashes

### PR DESCRIPTION
**Pull request by swashcap**
* **Problem:** Clicking “Log Out” crashes the UI (see #211).
* **Solution:** Pin `electron@1.5.1` until we can revise our remote main-to-render process architecture.
* **Testing:**
  1. Log in
  2. Log out
  3. Observe no hard crashes

### CODE REVIEW

**Comment by swashcap** [comment]
In three log in → log out attempts only the second and third log outs error:

three-attempts

Which is strange, right? Doesn't seem to be any pattern after that. Probably racing.

**Comment by swashcap** [comment]
CI’s flagging erroring builds as passes. Here’s 5cd2c0d295b6e04adca8819e7b66bd91154bebd1:

```shell
> coinstac@2.0.0 lint /home/rof/src/github.com/MRN-Code/coinstac
> eslint '**/*.js' '**/bin/*'


> coinstac@2.0.0 test /home/rof/src/github.com/MRN-Code/coinstac
> node scripts/test.js


> coinstac-client-core@2.4.0 test /home/rof/src/github.com/MRN-Code/coinstac/packages/coinstac-client-core
> npm run clean && nyc --reporter=lcov --check-coverage --functions=70 --branches=80 --lines 87 node test


> coinstac-client-core@2.4.0 clean /home/rof/src/github.com/MRN-Code/coinstac/packages/coinstac-client-core
> rm -rf .nyc_output coverage .tmp

TAP version 13
# ModelService basic
ok 1 ModelService is fn
ok 2 explodes without content
# ModelService extension
ok 3 extension GO!
# ModelService validation params
ok 4 passes callback param
ok 5 rejects without parameters
ok 6 passes onlyFields param
# ModelService validation
ok 7 passes props to validator
ok 8 passes validation error
ok 9 passes validation value
# AuthenticationService :: constructor
ok 10 extends Halfpenny
# AuthenticationService :: user storage
ok 11 sets empty user
ok 12 retrieves set user
ok 13 clears stored user
# AuthenticationService :: database credentials storage
ok 14 sets empty database credentials
ok 15 retrieves set database credentials
ok 16 clears database credentials
# AuthenticationService :: login/logout`
ok 17 calls Halfpenny login
ok 18 passes login response
ok 19 sets user on login
ok 20 sets database credentials on login
ok 21 calls Halfpenny logout
ok 22 clears database credentials on logout
ok 23 clears user on logout
# ComputationService :: modelServiceHooks
ok 24 returns db name
ok 25 returns Computation model
# ComputationService :: canStartComputation
ok 26 rejects when consortium lacks active computation ID
ok 27 rejects when not a consortium owner
ok 28 rejects when a run is active
ok 29 resolves when conditions suitable
# ComputationService :: doTriggerRunner errors
ok 30 rejects without consortium ID
ok 31 rejects without project ID
ok 32 rejects without run ID
Error: Project 's inputs must be re-entered
at Promise.all.then (/home/rof/src/github.com/MRN-Code/coinstac/packages/coinstac-client-core/src/sub-api/computation-service.js:9:2782)
at runMicrotasksCallback (internal/process/next_tick.js:58:5)
at _combinedTickCallback (internal/process/next_tick.js:67:7)
at process._tickCallback (internal/process/next_tick.js:98:9)
Error: Project undefined's inputs must be re-entered
at Promise.all.then (/home/rof/src/github.com/MRN-Code/coinstac/packages/coinstac-client-core/src/sub-api/computation-service.js:9:2782)
at runMicrotasksCallback (internal/process/next_tick.js:58:5)
at _combinedTickCallback (internal/process/next_tick.js:67:7)
at process._tickCallback (internal/process/next_tick.js:98:9)
ERROR: Coverage for branches (25.64%) does not meet global threshold (80%)
ERROR: Coverage for lines (34.62%) does not meet global threshold (87%)
ERROR: Coverage for functions (23.88%) does not meet global threshold (70%)
npm ERR! Test failed.  See above for more details.
Tests in /home/rof/src/github.com/MRN-Code/coinstac/packages/coinstac-client-core exitied with code 1
```

**Comment by swashcap** [comment]
““Fixing”” logout also addresses the data clearing problem (#213). A consecutive log in don’t persist the `projects` database, unfortunately. Refreshing Electron doesn’t cause projects to clear, but a hard quit-restart does.

**Comment by rssk** [comment]
^What? I thought projects should always be persisted, except when a `npm run clean` is ran or the delete user data button is clicked. Otherwise this looks fine.

**Comment by swashcap** [comment]
> I thought projects should always be persisted

That’s what I thought, too. 😕

**Pull request merged**
