### PR TITLE
npm fixes: lockfiles & electron versioning

### PR DESCRIPTION
**Pull request by swashcap**
* **Problem:**
    1. npm@5 doesn’t install all dependencies due to outdated lockfiles
    2. npm@5 changed exact version of electron to range on b76e63f81ae7a8e04ed8eca851160e08d82f4c7b
* **Solution:**
    1. Re-generate lockfiles
    2. Save exact version of electron (1.5.1)
* **Testing:** Make sure you’re using npm@5. Then:
    1. `npm run clean -- --yes`
    2. `npm run build`
    3. Ensure services run and UI boots w/o errors
    4. Ensure electron 1.5.1 is installed:

        ```shell
        $ cd packages/coinstac-ui
        $ npm ls electron
        └── electron@1.5.1 
        ```

### CODE REVIEW

**Review by tkah — APPROVED** [review]
:thumbsup:

**Comment by swashcap** [comment]
Okay, having trouble with the build script at 0b9d896e52cba03a9d94cb2eb40e1595c189c0ee:

```shell
NpmUtilities.installInDir     ("./packages/coinstac-ui", ["archiver@^1.3.0","babel-cli@^6.24.1","babel-core@^6.25.0","babel-loader@...)
npm WARN deprecated fs-promise@0.5.0: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated wrench@1.5.8: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm WARN prefer global marked@0.3.6 should be installed with -g
npm WARN prefer global node-ninja@1.0.2 should be installed with -g
npm WARN prefer global node-gyp@3.6.2 should be installed with -g
module.js:471
    throw err;
    ^

Error: Cannot find module 'ansi'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/creed/coinstac/packages/coinstac-ui/node_modules/prebuild/node_modules/gauge/progress-bar.js:3:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@1.4.6 install: `prebuild --install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leveldown@1.4.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/creed/.npm/_logs/2017-06-20T05_53_35_166Z-debug.log

Errored while running BootstrapCommand.execute
npm WARN deprecated fs-promise@0.5.0: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated wrench@1.5.8: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
npm WARN prefer global marked@0.3.6 should be installed with -g
npm WARN prefer global node-ninja@1.0.2 should be installed with -g
npm WARN prefer global node-gyp@3.6.2 should be installed with -g
module.js:471
    throw err;
    ^

Error: Cannot find module 'ansi'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/creed/coinstac/packages/coinstac-ui/node_modules/prebuild/node_modules/gauge/progress-bar.js:3:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! leveldown@1.4.6 install: `prebuild --install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the leveldown@1.4.6 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/creed/.npm/_logs/2017-06-20T05_53_35_166Z-debug.log
```

Probably another bad lock file state. Going to blow away the _package-lock.json_ files and retry. Fortunately, electron's pinned:

```
$ npm ls electron
coinstac-ui@2.5.0 /Users/creed/coinstac/packages/coinstac-ui
└── electron@1.5.1 
```

**Comment by swashcap** [comment]
Looks like running `npm run build` from the root modifies _coinstac-ui_’s _package.json_:

```diff
diff --git a/packages/coinstac-ui/package.json b/packages/coinstac-ui/package.json
index f3030ae..fa82870 100644
--- a/packages/coinstac-ui/package.json
+++ b/packages/coinstac-ui/package.json
@@ -55,7 +55,7 @@
     "cross-env": "^2.0.1",
     "css-loader": "^0.28.4",
     "devtron": "^1.4.0",
-    "electron": "1.5.1",
+    "electron": "^1.5.1",
     "electron-debug": "^1.1.0",
     "electron-packager": "^8.7.1",
     "file-loader": "^0.11.2",
```

Are you _kidding me?!_

**Comment by swashcap** [comment]
Via the [lerna creator](https://github.com/lerna/lerna/issues/856#issuecomment-304959008):

> Yeah it's [the `--hoist` flag] definetely not handled yet (nothing on npm 5 is supported since we haven't tested)

😕

**Comment by swashcap** [comment]
Okay, we **can’t use npm5**. After browsing lerna’s issues it’s clear our monorepo solution isn’t yet ready for it or Node.js 8+. Bootstrapping via `npm run build` in the root causes _package.json_ mutations, whereas _npm install_ in the packages’ directories doesn’t. 056071cc4e3b3b690719122f58eae88704191514 reverts the addition of _package-lock.json_ files.

**Comment by swashcap** [comment]
lockfiles are dropped, and npm’s version meddling is remedied. Multi-shot runs fine. _Mergin!_

**Pull request merged**
